services:
  merchants-db:
    image: mongo:latest
    hostname: merchants-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "${MERCHANTS_DB_PORT}:27017"
    volumes:
      - merchants_data_container:/data/db

  merchants-service:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"

volumes:
  merchants_data_container: