merchants = {
    "d3bc94e8-16ca-4d2e-a711-0ee3e1e42856": {
        "id": "d3bc94e8-16ca-4d2e-a711-0ee3e1e42856",
        "name": "Mama of Africa",
        "address": {
            "street": "Hauptstraße",
            "number": 10,
            "postalCode": "35390",
            "city": "Gießen"
        },
        "hours": {
            "0": [11,24],
            "1": [11,24],
            "2": [11,24],
            "3": [11,24],
            "4": [11,1],
            "5": [11,1],
            "6": [11,24],
        },
        'headerSrc': 'web',
        "headerImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYTUJTcRWNrVlhX3WfF74PffM50qgSejdzEg&usqp=CAU",
        "icon": "",
        'tags': [
            ("Vegan", 0xe532, 'Vegan restaurant in the style of a fastfood diner owned by animal rights activists. Offers burgers, loaded fries and also Israeli food like hummus in a lot of varieties. Open since July 2020.'),
            ("Access", 0xe03e, 'Das Restaurant ist komplett barrierefrei und nach einem Umbau stehen auch rollstuhlgerechte Toiletten zur Verfügung'),
        ],
        "description": "",
        "rating": 4.3,
        "services": [
            {
                'name': 'Buffet',
                'id': '34527dc4-cf30-4851-ace1-b066d944f7e5',
                'imageSrc': 'web',
                'image': "https://saednews.com/storage/media-center/images/__en__ac-image-XT1640585171Qj.jpeg",
                "timeSlots": [i for i in range(11,13+1)],
                'description': 'Ein Platz an unserem Mittagsbuffet (11:00 - 13:00 Uhr)',
                'maxGroupSize': 4,
                'maxPlaces': 4,
            },
            {
                "name": "Tischreservierung",
                "id": "b8082774tebe2",
                'imageSrc': 'web',
                'image': "https://i.ytimg.com/vi/uWJ-iQ9a7C0/maxresdefault.jpg",
                "timeSlots": [i for i in range(9,19+1)],
                "description": "",
                'maxGroupSize': 12,
                'maxPlaces': 4,
            },
            {
                "name": "Besondere Anlässe",
                "id": "2ad7dab6-aef6-4a99-9047-8f29182306c1",
                'imageSrc': 'web',
                'image': "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMisFPeSFz9Fl1r3UoV8zcXvS1Cxq1W2DaDQ&usqp=CAU",
                "timeSlots": [i for i in range(12,19+1)],
                "description": "",
                'maxGroupSize': 12,
                'maxPlaces': 1,
            }
        ],
        "category": 1,
    },
    "b8082774-ebe2-4aa6-8572-53aa9550b5c2": {
        "name": "Pastaholic",
        "address": {
            "street": "Westanlage",
            "number": 20,
            "postalCode": "35390",
            "city": "Gießen"
        },
        "hours": {
            "0": [11,24],
            "1": [11,24],
            "2": [11,24],
            "3": [11,24],
            "4": [11,1],
            "5": [11,1],
            "6": [11,24],
        },
        "id": "b8082774-ebe2-4aa6-8572-53aa9550b5c2",
        'headerSrc': 'web',
        "headerImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVkHxB_1-NMjF263IJiO4APkAToSiKHKWjug&usqp=CAU",
        "icon": "",
        'tags': [
            ("Vegan", 0xe532, 'Vegan restaurant in the style of a fastfood diner owned by animal rights activists. Offers burgers, loaded fries and also Israeli food like hummus in a lot of varieties. Open since July 2020.'),
            ("Access", 0xe03e, 'Das Restaurant ist komplett barrierefrei und nach einem Umbau stehen auch rollstuhlgerechte Toiletten zur Verfügung'),
        ],
        "description": "",
        "rating": 2.9,
        "services": [
            {
                'name': 'Mittagsangebot',
                "id": "b80827741234",
                'imageScr': 'web',
                'image': "https://images.lecker.de/herrlich-cremige-feel-good-pasta-f9187803,id=26ecd7a8,b=lecker,w=610,cg=c.jpg",
                "timeSlots": [i for i in range(12,19+1)],
                'description': 'Ein Platz an unserem Mittagsbuffet (11:00 - 13:30 Uhr)',
                'maxGroupSize': 12,
                'maxPlaces': 1,
            },
            {
                "name": "Tischreservierung",
                "id": "b80827742345",
                'imageScr': 'web',
                'image': "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg/377px-%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg",
                "timeSlots": [i for i in range(12,19+1)],
                "description": "",
                'maxGroupSize': 12,
                'maxPlaces': 1,
            }
        ],
        "category": 1,
    },
    "34527dc4-cf30-4851-ace1-b066d944f7e5": {
        "name": "Basilico",
        "address": None,
        "hours": None,
        "id": "34527dc4-cf30-4851-ace1-b066d944f7e5",
        'headerSrc': 'web',
        "headerImage": 'https://www.generationsforpeace.org/wp-content/uploads/2018/03/empty-300x240.jpg',
        "icon": "",
        'tags': [],
        "description": "",
        "rating": 5,
        "services": [],
        "category": 1,
    }
}
